### ISSUE TITLE
Makfile does not run on macos

### ISSUE THREAD

**Issue by felixbecker** [spreadshirt/f3#3]
Hi,

it looks like the Makefile hast issues on Macos.
The date function has been updated and the parameters are not valid anymore.
and the install Flags caused an error for me as well.

Changing: 
`GO_FLAGS	:=-ldflags="-X $(META_PACKAGE_IMPORT_PATH).Version=$(VERSION) -X $(META_PACKAGE_IMPORT_PATH).BuildTime=$(shell date --iso-8601=seconds --utc)"`
https://github.com/spreadshirt/f3/blob/master/Makefile#L6

To: 
```
DATE 		= $(shell date -u +"%Y-%m-%dT%H:%M:%SZ")
GO_FLAGS	:=-ldflags="-X $(META_PACKAGE_IMPORT_PATH).Version=$(VERSION) -X $(META_PACKAGE_IMPORT_PATH).BuildTime=$(DATE)"
```
did the trick for me. The issue was at: `date --iso-8601=seconds --utc`

and somehow this:
https://github.com/spreadshirt/f3/blob/master/Makefile#L17-L22
```
install: f3
ifeq ($$EUID, 0)
	@install --mode=0755 --verbose f3 /usr/local/bin
else
	@install --mode=0755 --verbose f3 $$HOME/.local/bin
endif
```
needed to be changed to: 

```
install: f3
ifeq ($$EUID, 0)
	@install -m 0755 -v f3 /usr/local/bin
else
	@install -m 0755 -v f3 $$HOME/.local/bin
endif
```
After those changes the script ran.

Don't know if you prefer pull requests or want to submit the changes by yourself? Obviously I can only speak for Macos here.

**Comment by klingtnet** [comment]
Thank your for the contribution! I haven't tested it on MacOS because I'm only running linux.
The problem on MacOS is probably that the `date` tool is multiple years old and/or different from GNU pendant.
You do not need to open a pull request, instead I will try to dynamically select the correct command depending on the system.

**Comment by felixbecker** [comment]
Thanx for getting back :) 

I found the info about the deprecation of the parameters of the date command here: 
https://unix.stackexchange.com/questions/164826/date-command-iso-8601-option
and the alternative solution(s) here:
https://zxq9.com/archives/795

btw: the Dockerfile also contains a typo here:
https://github.com/spreadshirt/f3/blob/master/Dockerfile#L8
I think it should be `S3_CREDENTIALS`

When you are thinking about selecting things dynamically, it would be great to pass in the `GOOS` as well. Because if I would like to run it locally it should compile to GOOS=darwin when running in the linux container GOOS=linux.

I hope it is ok for to through the findings at you :-)

**Comment by klingtnet** [comment]
@felixbecker I would propose the following, first I fix the Makefile to dynamically choose the commands and second you open a PR to add cross-compilation support?

PS: Thanks for pointing out the typo in the Dockerfile.

**Comment by klingtnet** [comment]
@felixbecker Can you checkout the `fix-makefile-for-mac-os` branch please and confirm that it builds now?

**Comment by felixbecker** [comment]
It builds! perfect.. 
One small thing ... it moves the binaries to `$HOME/.local/bin`
and this is not executable (at least for me).
If you would do it like this ` $$GOPATH/bin` you could possibly go rid of the if/else branch since  $$GOPATH/bin is mapped as executable. Thats basically the same thing as you do `go install .`

**Comment by klingtnet** [comment]
User-wide installations will now use `vgo install ./cmd/f3` which installs directly into `$GOPATH/bin`: https://github.com/spreadshirt/f3/commit/0e0fab3e1f626bc2ac70c702cc1341a196f38185
